server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  mail:
    host: smtp.qq.com
    username: 1136135963@qq.com
    password: ikzluwurbmyjjdgc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
        auth: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.whq.mvc.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.whq.mvc: debug
